# Generated by Django 4.1.7 on 2023-04-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accept_language",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=250, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
